routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register');
Route::any('/logout', 'Auth\LoginController@logout')->name('logout');

Route::resource('campamento', 'CampamentoController')->middleware('auth');
Route::get('get/ciudades/{dpto?}','CampamentoController@getCiudades')->name('getCity');
Route::get('maqueta',function(){
	return view('maqueta');
})->name('maqueta');

app/Campamento.php
<?php

namespace Campamento;

use Illuminate\Database\Eloquent\Model;

class Campamento extends Model
{
    protected $fillable = ['nombre','correo','ciudad_id','hectareas','latitud','longitud'];

    public function ciudad()
    {
    	return $this->belongsTo('Campamento\Ciudad','ciudad_id');
    }

}

app/Ciudad.php
<?php

namespace Campamento;

use Illuminate\Database\Eloquent\Model;

class Ciudad extends Model
{
    protected $table = 'ciudades';
}

app/User.php
<?php

namespace Campamento;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CampamentoController.php
<?php

namespace Campamento\Http\Controllers;
use Campamento\Campamento;
use Campamento\Ciudad;

use Illuminate\Http\Request;
use Validator;

class CampamentoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Campamento::with('ciudad')->get();
        $title = 'Campamentos';
        $share = compact('data','title');
        return view('campamento.index',$share);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = 'Crear campamento';
        $campamento=new Campamento();
        $method=route('campamento.store');
        $dep = \DB::table('departamentos')->get();
        $share = compact('title','dep','campamento','method');
        return view('campamento.create',$share);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'nombre' => 'alpha',
            'correo' => 'email',
            'hectareas' => 'numeric',
            'latitud' => 'numeric',
            'longitud' => 'numeric',
        ])->validate();

        Campamento::create($request->all());
        return redirect(route('campamento.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $title = 'Ver campamento';
        $campamento= Campamento::find($id);
        $method='';
        $event = 'SHOW';
        $dep = \DB::table('departamentos')->get();
        $campamento->departamento = $campamento->ciudad->departamento_id;
        $share = compact('title','dep','campamento','method','event');
        return view('campamento.create',$share);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $title = 'Editar campamento';
        $campamento= Campamento::find($id);
        $method=route('campamento.update',$id);
        $event = 'PATCH';
        $dep = \DB::table('departamentos')->get();
        $campamento->departamento = $campamento->ciudad->departamento_id;
        $share = compact('title','dep','campamento','method','event');
        return view('campamento.create',$share);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Validator::make($request->all(), [
            'nombre' => 'alpha',
            'correo' => 'email',
            'hectareas' => 'numeric',
            'latitud' => 'numeric',
            'longitud' => 'numeric',
        ])->validate();

        $campamento = Campamento::find($id);
        $campamento->update($request->all());

        return redirect(route('campamento.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Campamento::findOrFail($id)->delete();
        return back();
    }

    public function getCiudades($dpto,Request $request)
    {
        if($dpto>0){
            $res = Ciudad::where('departamento_id',$dpto)
                    ->where(function ($_this) use($request){
                        if($request->get('search')){
                            $_this->where('nombre','like',"%".$request->get('search')."%");
                        }
                    })
                    ->get(['id','nombre']);
            return response()->json($res,200);
        }else{
            return response()->json([],200);
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace Campamento\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace Campamento\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/campamento/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">

		<div class="row">

			<div class="col-md-12">
				<nav aria-label="breadcrumb">
				  <ol class="breadcrumb">
				    	<h1 >Crear campamento </h1>
				  </ol>
				</nav>
			</div>

			<div class="col-md-12">
				<div class="card p-2">
					
				<form method="post"  action="{{ $method }}">
					<div class="row">
						@csrf
						@if(isset($event))
							@method($event)
						@endif

						<div class="form-group col-md-6">
							<label for="exampleInputEmail1">Nombre</label>
							<input type="text" value="{{ old('nombre') ?: $campamento->nombre  }}" name="nombre" class="form-control" required >
						</div>

						<div class="form-group col-md-6">
							<label for="exampleInputPassword1">Correo</label>
							<input type="email" value="{{ old('correo') ?: $campamento->correo  }}" name="correo"  class="form-control" required>
						</div>

						<div class="form-group col-md-6">
							<label for="exampleInputEmail1">Departamento</label>
							<select required class="form-control" id="departamento">
								<option></option>
								@foreach($dep as $item)
									<option value="{{$item->id}}">{{$item->nombre}}</option>
								@endforeach
							</select>
						</div>

						<div class="form-group col-md-6">
							<label for="exampleInputPassword1">Ciudad</label>
							<select required disabled class="form-control" id="ciudad">
								@if(isset($campamento->ciudad->nombre))
									<option>{{$campamento->ciudad->nombre}}</option>
								@endif
							</select>
							<input type="hidden" value="{{ old('ciudad_id') ?: $campamento->ciudad_id  }}" name="ciudad_id" id="ciudad_id" >
						</div>

						<div class="form-group col-md-4">
							<label for="exampleInputPassword1">Hectáreas</label>
							<input type="number" value="{{ old('hectareas') ?: $campamento->hectareas  }}" name="hectareas" class="form-control" required>
						</div>

						<div class="form-group  ubicacion col-md-4" style="display: {{isset($campamento->ciudad_id) ? 'block' : 'none'}};">
							<label for="exampleInputPassword1">Latitud</label>
							<input type="text" value="{{ old('latitud') ?: $campamento->latitud  }}" name="latitud" class="form-control" required>
						</div>

						<div class="form-group  ubicacion col-md-4" style="display: {{isset($campamento->ciudad_id) ? 'block' : 'none'}};">
							<label for="exampleInputPassword1">Longitud</label>
							<input type="text" value="{{ old('longitud') ?: $campamento->longitud  }}" name="longitud" class="form-control" required>
						</div>

						<div class="col-md-12">
				            <br>
				            @if(isset($event) and $event!='SHOW')
								<button type="submit" class="btn btn-primary">Guardar</button>
							@endif
							<a href="{{route('campamento.index')}}" class="btn btn-info">Volver</a>
						</div>
					</div>
				</form>
				<br>
					@if ($errors->has('nombre'))
		                  <span class="alert bg-danger"><b>Nombre incorrecto, este valor solo permite texto.</b></span>
		            @endif
					@if ($errors->has('coreo'))
		                  <div class="alert bg-danger"><b>Correo invalido.</b></div>
		            @endif
					@if ($errors->has('latitud'))
		                  <div class="alert bg-danger"><b>Latitud no tiene el formato correcto.</b></div>
		            @endif
					@if ($errors->has('longitud'))
		                  <div class="alert bg-danger"><b>Longitud no tiene el formato correcto.</b></div>
		            @endif
		            @if ($errors->has('hectareas'))
		                  <div class="alert bg-danger"><b>Hectáreas solo permite números.</b></div>
		            @endif
				</div>
			</div>	

		</div>
	</div>

@stop

@section('scripts')
	<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
	<script type="text/javascript">
		window.dpto = 0;
		window.preload = true;
		$(document).ready(function() {

			onloadDpto();

			@if(isset($campamento->departamento))
				window.preload = false;
				$('#departamento').val({{$campamento->departamento}}).trigger('change');
			@endif

		});

		function onloadDpto() {
			$('#departamento').select2().on('change', function () {
				    if(this.value.length){
				    	window.dpto = this.value;
				    	$('#ciudad').attr('disabled',false);
				    	if (window.preload) {
				    		$('#ciudad_id').val('');
				    		instanceCiudad();
						}
						window.preload=true;
				    }else{
				    	window.dpto = 0;
				    	$('#ciudad').attr('disabled',true);
				    	$('#ciudad_id').val('');
				    }
			});
		}

		function instanceCiudad() {
			$('#ciudad').select2({
			  ajax: {
			    url: '{{route('getCity')}}/'+window.dpto,
			    dataType: 'json',
			    data: function (params) {
			      var query = {
			        search: params.term,
			      }
			      return query;
			    },
			    processResults: function (data) {
		            return {
		                results: $.map(data, function (item) {
		                    return {
		                        text: item.nombre,
		                        id: item.id
		                    }
		                })
		            };
		        }
			  }
			}).on('change', function () { 
				$('#ciudad_id').val(this.value);
				$('.ubicacion').show();
			});
			$("#ciudad").val(null).trigger('change');
			$('.ubicacion').hide();
		}

	</script>
@stop

resources/views/campamento/index.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">

		<div class="row">

			<div class="col-md-12">
				<nav aria-label="breadcrumb">
				  <ol class="breadcrumb">
				    <div class="breadcrumb-item active" aria-current="page">
				    	<h1 class="d-inline">Campamentos </h1>
				    	&nbsp;
				    	<a  href="{{route('campamento.create')}}" class="btn btn-success btn-lg float-right">Crear</a>
				    </div>
				  </ol>
				</nav>
			</div>

			<div class="col-md-12">
				<table class="table" style="background: #fff">
					<thead class="thead-light">
						<tr>
							<th width="40%">Nombre</th>
							<th>Ciudad</th>
							<th>Hectáreas</th>
							<th>&nbsp;</th>
						</tr>
					</thead>
					<tbody>
						@if($data->count())
							@foreach($data as $value)
								<tr>
							      <td>{{$value->nombre}}</td>
							      <td>{{$value->ciudad->nombre}}</td>
							      <td>{{$value->hectareas}}</td>
							      <td>
							      	<a href="{{route('campamento.edit',$value->id)}}" class="btn btn-warning">Editar</a>
							      	<a href="{{route('campamento.show',$value->id)}}" class="btn btn-info">Ver</a>
							      	<form class="d-inline" method="post" action="{{route('campamento.destroy',$value->id)}}">
							      		@method("DELETE")
							      		@csrf
							      		<button class="btn btn-danger">Eliminar</button>
							      	</form>
							      </td>
							    </tr>
							@endforeach
						@else
							<tr>
								<td colspan="3">
					    			Sin registros
								</td>
							</tr>
						@endif
					</tbody>
				</table>
			</div>	

		</div>
	</div>

@stop

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ isset($title) ? $title : config('app.name', 'Laravel') }}</title>
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <style type="text/css">
        .select2-selection__rendered {
          line-height: 32px !important;
        }

        .select2-selection {
          height: 36px !important;
        }
    </style>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <img src="{{asset('img/logo.png')}}" height="50">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}" ></script>
@yield('scripts')
</html>

resources/views/layouts/simple.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Mauqueta Boostrap</title>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" ></script>
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
</head>
<body>

    @yield('content')

</body>
</html>

resources/views/maqueta.blade.php
@extends('layouts.simple')

@section('content')

	<div class="container-fluid">
	<div class="row">
		<div class="col-md-12 p-3 bg-info">
			<a class="navbar-brand" href="{{ url('/') }}">
                <img src="{{asset('img/logo.png')}}" height="80">
            </a>
		</div>
		<div class="col-md-12 bg-dark">
			<nav class="navbar navbar-expand-lg text-white">
				 
				<button class="navbar-toggler bg-white" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="navbar-toggler-icon "></span>
				</button> 
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="navbar-nav">
						<li class="nav-item active ">
							 <a class="nav-link text-white" href="#">Inicio <span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item ">
							 <a class="nav-link text-white" href="#">Tendencia</a>
						</li>
						<li class="nav-item dropdown ">
							<a class="nav-link dropdown-toggle text-white" href="#" 
							id="navbarDropdownMenuLink" data-toggle="dropdown">Más categorias</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
								 <a class="dropdown-item" href="#">Deportes</a> 
								 <a class="dropdown-item" href="#">Tecnología</a> 
								 <a href="#" class=" dropdown-item dropdown-toggle" data-toggle="dropdown">Nacional</a>
	                            <ul class="dropdown-menu">
	                                <li><a class="dropdown-item">Action</a></li>
	                                <li class="divider"></li>
	                                <li class="dropdown-submenu">
	                                    <a href="#" class="dropdown-item dropdown-toggle" data-toggle="dropdown">Dropdown</a>
	                                    <ul class="dropdown-menu">
	                                       <li><a>Action</a></li>
	                                    </ul>
	                                </li>
	                            </ul>
							</div>
						</li>
					</ul>
					<ul class="navbar-nav ml-md-auto d-none d-sm-block">
						<li>
							<form class="form-inline">
								<input class="form-control mr-sm-2" type="text"> 
								<button class="btn btn-success my-2 my-sm-0" type="submit">
									Buscar noticias
								</button>
							</form>
						</li>
					</ul>
				</div>
			</nav>
			<div class="d-block d-sm-none" >
				<form class="form-inline" align="center">
					<input class="form-control col-9 mr-sm-2 mr-2" type="text"> 
					<button class="btn btn-success my-2 my-sm-0" type="submit">
						Buscar
					</button>
				</form>
			</div>
		</div>
	</div>

	<div class="row m-3">
		<div class="col-md-12 ">
			<div class="row">
				<div class="col-md-8">
					<div class="jumbotron">
						<h2>
							Ballena de 12 metros hecha de plásticos es arte en Bélgica
						</h2>
						<p>
							En la Trienal de Brujas, en Bélgica, se instaló la figura de ballena de 12 metros de altura construida con cinco toneladas de desechos...
						</p>
						<p>
							<a class="btn btn-primary btn-large" href="#">Leer más</a>
						</p>
					</div>
					<div class="row">
						<div class="col-md-5 bg-white p-3 mt-2 ml-2 mr-1">
							<h2>
								Silleteros recorren las calles de Nueva York este domingo
							</h2>
							<p>
								En Queens, Nueva York, avanza la celebración del Flower Festival 2018, encuentro anual de la colonia colombiana en esa ciudad, que...
							</p>
							<p>
								<a class="btn" href="#">Ver detalles »</a>
							</p>
						</div>
						<div class="col-md-5 bg-white p-3 mt-2 ml-2 mr-1">
							<h2>
								Ojo: la silla de niños sí es importante en el carro
							</h2>
							<p>
								No es solo montarlos a pasear. Su seguridad debe ser una prioridad, adaptada a sus necesidades. No es comprar cualquier silla en descuento....
							</p>
							<p>
								<a class="btn" href="#">Ver detalles »</a>
							</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-5 bg-white p-3 mt-2 ml-2 mr-1">
							<h2>
								Así llegaron los primeros perros a Estados Unidos según un estudio
							</h2>
							<p>
								Los primeros perros que habitaron Estados Unidos llegaron de la vasta región de Siberia (Rusia) hace unos 9.000 años y desaparecieron...
							</p>
							<p>
								<a class="btn" href="#">Ver detalles »</a>
							</p>
						</div>
						<div class="col-md-5 bg-white p-3 mt-2 ml-2 mr-1">
							<h2>
								Hoy es el día en que la Tierra está más lejos del Sol
							</h2>
							<p>
								Hoy a las 11:47 de la mañana hora local, la Tierra estará en su punto más alejado del Sol de todo el año. A esa hora se encontrará...
							</p>
							<p>
								<a class="btn" href="#">Ver detalles »</a>
							</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 mt-3">
					<h2>
						Última hora
					</h2>
					<div class="row">
						<div class="col-md-12">
							<h3>Deportes</h3>
						</div>
						<div  class="col-md-6 col-4 p-2">
							<img alt="Bootstrap Image Preview" src="https://www.layoutit.com/img/sports-q-c-140-140-3.jpg">
						</div>
						<div  class="col-md-6 col-4 p-2">
							<img alt="Bootstrap Image Preview" src="https://www.layoutit.com/img/sports-q-c-140-140-3.jpg">
						</div>
						<div  class="col-md-6 col-4 p-2">
							<img alt="Bootstrap Image Preview" src="https://www.layoutit.com/img/sports-q-c-140-140-3.jpg">
						</div>
						<div  class="col-md-6 col-4 p-2">
							<img alt="Bootstrap Image Preview" src="https://www.layoutit.com/img/sports-q-c-140-140-3.jpg">
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<h3>Entretenimiento</h3>
						</div>
						<div  class="col-md-6 col-4 p-2">
							<img alt="Bootstrap Image Preview" src="https://www.layoutit.com/img/sports-q-c-140-140-3.jpg">
						</div>
						<div  class="col-md-6 col-4 p-2">
							<img alt="Bootstrap Image Preview" src="https://www.layoutit.com/img/sports-q-c-140-140-3.jpg">
						</div>
						<div  class="col-md-6 col-4 p-2">
							<img alt="Bootstrap Image Preview" src="https://www.layoutit.com/img/sports-q-c-140-140-3.jpg">
						</div>
						<div  class="col-md-6 col-4 p-2">
							<img alt="Bootstrap Image Preview" src="https://www.layoutit.com/img/sports-q-c-140-140-3.jpg">
						</div>
					</div>
					<div class="page-header">
						<h1>
							Más categorías
						</h1>
					</div>
					<ul>
						<li class="list-item">
							Cultura
						</li>
						<li class="list-item">
							Política
						</li>
						<li class="list-item">
							Negocios
						</li>
						<li class="list-item">
							Internacional
						</li>
						<li class="list-item">
							Colombia
						</li>
					</ul>
				</div>
			</div>
			<div class="row m-3 d-none d-sm-block">
				<div class="col-md-12">
					<div class="carousel slide" id="carousel-336885">
						<ol class="carousel-indicators">
							<li data-slide-to="0" data-target="#carousel-336885">
							</li>
							<li data-slide-to="1" data-target="#carousel-336885" class="active">
							</li>
							<li data-slide-to="2" data-target="#carousel-336885">
							</li>
						</ol>
						<div class="carousel-inner">
							<div class="carousel-item active carousel-item-left">
								<img class="d-block w-100" alt="Carousel Bootstrap First" src="https://www.layoutit.com/img/sports-q-c-1600-500-1.jpg">
								<div class="carousel-caption">
									<h4>
										First Thumbnail label
									</h4>
									<p>
										Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
									</p>
								</div>
							</div>
							<div class="carousel-item carousel-item-next carousel-item-left">
								<img class="d-block w-100" alt="Carousel Bootstrap Second" src="https://www.layoutit.com/img/sports-q-c-1600-500-2.jpg">
								<div class="carousel-caption">
									<h4>
										Second Thumbnail label
									</h4>
									<p>
										Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
									</p>
								</div>
							</div>
							<div class="carousel-item">
								<img class="d-block w-100" alt="Carousel Bootstrap Third" src="https://www.layoutit.com/img/sports-q-c-1600-500-3.jpg">
								<div class="carousel-caption">
									<h4>
										Third Thumbnail label
									</h4>
									<p>
										Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
									</p>
								</div>
							</div>
						</div> <a class="carousel-control-prev" href="#carousel-336885" data-slide="prev"><span class="carousel-control-prev-icon"></span> <span class="sr-only">Previous</span></a> <a class="carousel-control-next" href="#carousel-336885" data-slide="next"><span class="carousel-control-next-icon"></span> <span class="sr-only">Next</span></a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12 p-3 bg-info">
			<h3 class="text-center text-white">LaraCamp 2018</h3>
		</div>
	</div>

</div>

@stop